[package]
name = "rust_ray_tracing"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.11"
winit = "0.28"
pixels = "0.12"
egui = "0.21"
egui-winit = "0.21"
egui_extras = "0.21"
egui-wgpu = "0.21"

[profile.dev]
opt-level = 3
